### ISSUE TITLE
Cannot ping an AWS cell using go v1.15

### ISSUE THREAD

**Issue by hidalgopl** [elotl/kip#176]
I built kip locally with go v1.15 and I'm mounting it as a volume, as described here: https://github.com/elotl/kip-minikube/

It starts normally, but when I tried to run nginx on virtual node, it seems that node_controller cannot (first few tries result in connection refused, but I guess it's expected as EC2 instance is booting) ping the cell:
```
W0914 14:20:52.134617       7 node_controller.go:509] Heartbeat error from node d222e754-34f0-4667-b117-2d52e1f1e2b6: Get "https://3.227.243.231:6421/rest/v1/ping": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
```
It's not an issue for me right now, as I can always use `v1.13`, but I guess we need to tackle it sooner or later.

Found this discussion: https://github.com/golang/go/issues/39568

**Comment by henryprecheur** [comment]
FYI: after 3 days trying to get the minikube cluster work I wasn’t able to reproduce the issue. I’m pretty sure the patch fixes it.

3 days is way too much time to spend on this, so I just merged the PR. I don’t think there is much value to be created with me spending another day confirming the bug is fixed.
